Repository 0neGal/viper, pull requests merged in 2022-03, with the labels that each got.

#93 fix: nsargs clearing when edited outside of Viper
  src/app/main.js
  src/utils.js
Labels: bug

#97 fix: VDF path searching not working on SteamDeck
  src/extras/findgame.js
  src/utils.js
Labels: bug, help wanted

#106 feat: Add missing French translation keys
  src/lang/fr.json
Labels: localization
