Repository 0neGal/viper, pull requests merged in 2022-01, with the labels that each got.

#16 chore: Auto updating
  PUBLISH.md
  README.md
  docs/viper.1
  docs/viper.1.md
  package-lock.json
  package.json
  src/app/main.js
  src/cli.js
  src/index.js
  src/lang/en.json
  src/lang/fr.json
  src/utils.js
Labels: enhancement

#24 fix: No game path
  src/app/main.js
  src/index.js
  src/lang/en.json
  src/lang/fr.json
  src/utils.js
Labels: bug, enhancement

#27 fix: Rate limit
  package-lock.json
  package.json
  src/requests.js
  src/utils.js
Labels: enhancement

#19 Mod support
  docs/viper.1
  docs/viper.1.md
  package-lock.json
  package.json
  src/app/index.html
  src/app/main.css
  src/app/main.js
  src/cli.js
  src/index.js
  src/lang/en.json
  src/lang/fr.json
  src/utils.js
Labels: enhancement

#32 fix: Displaying northstar version on first launch
  src/index.js
Labels: bug

#33 feat: Northstar auto-updates
  src/lang/en.json
  src/lang/fr.json
  src/utils.js
Labels: enhancement

#26 feat: New UI
  package-lock.json
  package.json
  src/app/fonts/Roboto-Black.ttf
  src/app/fonts/Roboto-BlackItalic.ttf
  src/app/fonts/Roboto-Bold.ttf
  src/app/fonts/Roboto-BoldItalic.ttf
  src/app/fonts/Roboto-Italic.ttf
  src/app/fonts/Roboto-Light.ttf
  src/app/fonts/Roboto-LightItalic.ttf
  src/app/fonts/Roboto-Medium.ttf
  src/app/fonts/Roboto-MediumItalic.ttf
  src/app/fonts/Roboto-Regular.ttf
  src/app/fonts/Roboto-Thin.ttf
  src/app/fonts/Roboto-ThinItalic.ttf
  src/app/fonts/import.css
  src/app/icons/close.png
  src/app/icons/northstar.png
  src/app/icons/titanfall2.png
  src/app/icons/viper.png
  src/app/index.html
  src/app/launcher.js
  src/app/main.css
  src/app/main.js
  src/app/roboto.ttf
  src/assets/bg/northstar.jpg
  src/assets/bg/tf2.jpg
  src/assets/bg/viper.jpg
  src/assets/ns.png
  src/assets/vanilla.png
  src/index.js
  src/lang/en.json
  src/lang/fr.json
  src/requests.js
  src/utils.js
Labels: enhancement

#49 Add minimize button
  src/app/icons/minimize.png
  src/app/index.html
  src/app/main.css
  src/index.js
Labels: enhancement

#46 Adding documentation/comments
  src/app/lang.js
  src/app/launcher.js
  src/app/main.js
  src/cli.js
  src/index.js
  src/lang.js
  src/requests.js
  src/utils.js
Labels: documentation

#58 Add spanish translation
  src/lang/es.json
Labels: localization

#60 Add new icon
  src/app/icons/viper.png
  src/assets/icons/512x512.png
  src/assets/icons/icon.ico
Labels: enhancement
