Repository 0neGal/viper, pull requests merged in 2022-02, with the labels that each got.

#64 Spanish localization for thunderstore support
  src/lang/es.json
Labels: localization

#65 Improve ease of install
  README.md
  assets/download.png
Labels: documentation

#68 Update es.json
  src/lang/es.json
Labels: localization

#50 Thunderstore support
  package-lock.json
  package.json
  src/app/browser.js
  src/app/icons/no-image.png
  src/app/index.html
  src/app/main.css
  src/app/main.js
  src/index.js
  src/lang/en.json
  src/lang/es.json
  src/lang/fr.json
  src/utils.js
Labels: enhancement

#71 Updated localization for toast notifications
  src/lang/es.json
Labels: localization

#73 fix: Excluded files
  src/utils.js
Labels: bug

#83 feat: Spanish "gui.mods.dragdrop" key
  src/lang/es.json
Labels: localization

#81 feat: drag and drop to install mods
  src/app/icons/download.png
  src/app/index.html
  src/app/main.css
  src/app/main.js
  src/index.js
  src/lang/en.json
  src/lang/es.json
  src/lang/fr.json
  src/utils.js
Labels: enhancement

#84 refactor: i18n
  src/lang.js
Labels: localization

#89 feat: Settings page: add "es" localization
  src/lang/es.json
Labels: localization

#90 [feat] french settings translations
  src/lang/fr.json
Labels: localization

#85 feat: Settings page
  src/app/browser.js
  src/app/icons/apply.png
  src/app/icons/settings.png
  src/app/index.html
  src/app/main.css
  src/app/main.js
  src/app/settings.js
  src/index.js
  src/lang/en.json
  src/lang/es.json
  src/lang/fr.json
  src/utils.js
Labels: enhancement, localization needed
