Repository 0neGal/viper, pull requests merged in 2023-07, with the labels that each got.

#192 Added Spanish strings for plugin install prompt
  src/lang/es.json
Labels: localization

#194 Add missing Spanish localizations
  src/lang/es.json
Labels: localization

#196 translate
  src/lang/fr.json
Labels: localization

#195 french trads
  src/lang/fr.json
Labels: localization

#198 German translation.
  src/lang/de.json
Labels: localization

#197 German translation.
  src/lang/de.json
Labels: localization

#193 i18n: add missing localization strings
  src/lang/de.json
  src/lang/es.json
  src/lang/fr.json
Labels: localization

#191 feat: Support for the new packages folder
  src/app/js/browser.js
  src/app/js/mods.js
  src/app/main.js
  src/index.js
  src/lang/de.json
  src/lang/en.json
  src/lang/es.json
  src/lang/fr.json
  src/modules/mods.js
  src/modules/packages.js
Labels: enhancement

#201 Fixed formatting issue in the up-to-date console message.
  src/modules/update.js
Labels: bug, localization

#203 Update maintainers.json
  src/lang/maintainers.json
Labels: localization
