Repository 0neGal/viper, pull requests merged in 2023-04, with the labels that each got.

#181 Fixes broken JSON files on restart
  src/app/main.js
Labels: bug

#186 Update es.json
  src/lang/es.json
Labels: localization

#183 feat: Support EA Desktop better
  src/lang/de.json
  src/lang/en.json
  src/lang/es.json
  src/lang/fr.json
  src/modules/is_running.js
  src/modules/kill.js
Labels: enhancement
